[2025-10-13T08:37:15.210+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:37:15.240+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T08:37:15.250+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T08:37:15.251+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:37:15.266+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-03 00:00:00+00:00
[2025-10-13T08:37:15.275+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=263) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:37:15.276+0000] {standard_task_runner.py:72} INFO - Started process 266 to run task
[2025-10-13T08:37:15.277+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpri__ga85']
[2025-10-13T08:37:15.279+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask extract_load_group.load_marketing_campaigns
[2025-10-13T08:37:15.351+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:37:15.456+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-13T08:37:15.458+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:37:18.196+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:18.213+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251013T083715, end_date=20251013T083718
[2025-10-13T08:37:18.231+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:37:18.231+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 39 for task extract_load_group.load_marketing_campaigns (403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.; 266)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:18.302+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-13T08:37:18.312+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:55:12.038+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:55:12.059+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T08:55:12.068+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T08:55:12.069+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:55:12.088+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-03 00:00:00+00:00
[2025-10-13T08:55:12.096+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=811) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:55:12.098+0000] {standard_task_runner.py:72} INFO - Started process 820 to run task
[2025-10-13T08:55:12.098+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmppuojywq8']
[2025-10-13T08:55:12.099+0000] {standard_task_runner.py:105} INFO - Job 133: Subtask extract_load_group.load_marketing_campaigns
[2025-10-13T08:55:12.156+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:55:12.254+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-13T08:55:12.255+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:55:21.549+0000] {load.py:30} INFO - Loaded 83 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-13T08:55:21.549+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:55:21.565+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:55:21.565+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251013T085512, end_date=20251013T085521
[2025-10-13T08:55:21.630+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:55:21.653+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:55:21.656+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:21:10.692+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:21:10.714+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T09:21:10.728+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T09:21:10.729+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:21:10.744+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-03 00:00:00+00:00
[2025-10-13T09:21:10.752+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1378) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:21:10.754+0000] {standard_task_runner.py:72} INFO - Started process 1388 to run task
[2025-10-13T09:21:10.755+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '195', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp6dw8p88w']
[2025-10-13T09:21:10.756+0000] {standard_task_runner.py:105} INFO - Job 195: Subtask extract_load_group.load_marketing_campaigns
[2025-10-13T09:21:10.812+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:21:10.919+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-13T09:21:10.921+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:21:21.867+0000] {load.py:30} INFO - Loaded 83 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-13T09:21:21.868+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:21:21.880+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:21:21.881+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251013T092110, end_date=20251013T092121
[2025-10-13T09:21:21.925+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:21:21.947+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:21:21.950+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:21:09.790+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:21:09.820+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:21:09.838+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:21:09.839+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:21:09.865+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-03 00:00:00+00:00
[2025-10-14T04:21:09.875+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=358) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:21:09.878+0000] {standard_task_runner.py:72} INFO - Started process 364 to run task
[2025-10-14T04:21:09.879+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpu38vvevv']
[2025-10-14T04:21:09.882+0000] {standard_task_runner.py:105} INFO - Job 288: Subtask extract_load_group.load_marketing_campaigns
[2025-10-14T04:21:09.966+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:21:10.091+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-14T04:21:10.093+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:21:15.091+0000] {load.py:30} INFO - Loaded 83 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-14T04:21:15.092+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:21:15.106+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:21:15.107+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251014T042109, end_date=20251014T042115
[2025-10-14T04:21:15.156+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:21:15.179+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:21:15.181+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:29:04.138+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:29:04.163+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:29:04.173+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:29:04.174+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:29:04.190+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-03 00:00:00+00:00
[2025-10-14T04:29:04.199+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=854) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:29:04.201+0000] {standard_task_runner.py:72} INFO - Started process 855 to run task
[2025-10-14T04:29:04.205+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '397', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp4eg22p48']
[2025-10-14T04:29:04.206+0000] {standard_task_runner.py:105} INFO - Job 397: Subtask extract_load_group.load_marketing_campaigns
[2025-10-14T04:29:04.277+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:29:04.383+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-14T04:29:04.385+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:29:09.173+0000] {load.py:30} INFO - Loaded 83 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-14T04:29:09.174+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:29:09.190+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:29:09.191+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251014T042904, end_date=20251014T042909
[2025-10-14T04:29:09.238+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:29:09.269+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:29:09.272+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:35:59.233+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:35:59.256+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:35:59.266+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:35:59.267+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:35:59.285+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_marketing_campaigns> on 2025-09-03 00:00:00+00:00
[2025-10-14T04:35:59.293+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1201) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:35:59.295+0000] {standard_task_runner.py:72} INFO - Started process 1204 to run task
[2025-10-14T04:35:59.296+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_marketing_campaigns', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '468', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpxye27suz']
[2025-10-14T04:35:59.298+0000] {standard_task_runner.py:105} INFO - Job 468: Subtask extract_load_group.load_marketing_campaigns
[2025-10-14T04:35:59.373+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_marketing_campaigns scheduled__2025-09-03T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:35:59.501+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_marketing_campaigns' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-14T04:35:59.502+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:36:03.208+0000] {load.py:30} INFO - Loaded 83 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_marketing_campaigns
[2025-10-14T04:36:03.209+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:36:03.221+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:36:03.221+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_marketing_campaigns, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251014T043559, end_date=20251014T043603
[2025-10-14T04:36:03.287+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:36:03.316+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:36:03.320+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
