[2025-10-14T04:15:50.822+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:15:50.843+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:15:50.853+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:15:50.854+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:15:50.867+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:15:50.874+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=147) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:15:50.875+0000] {standard_task_runner.py:72} INFO - Started process 148 to run task
[2025-10-14T04:15:50.875+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'transform', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp2mndjv1r']
[2025-10-14T04:15:50.877+0000] {standard_task_runner.py:105} INFO - Job 247: Subtask transform
[2025-10-14T04:15:50.926+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:15:51.002+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:15:51.002+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:15:51.748+0000] {transform.py:140} INFO - Executing dwh_ddl.sql query:
CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.fact_sales (
        transaction_id INT64,
        customer_id INT64,
        product_id INT64,
        quantity INT64,
        price INT64
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_customers (
        customer_id STRING,
        name STRING,
        email STRING,
        city STRING,
        signup_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_products (
        product_id INT64,
        product_name STRING,
        category STRING,
        price FLOAT64,
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_dates (
        transaction_id INT64,
        transaction_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_campaigns (
        campaign_id INT64,
        campaign_name STRING,
        start_date DATE,
        end_date DATE,
        channel STRING
    );
[2025-10-14T04:15:58.241+0000] {transform.py:148} INFO - query executed successfully.
[2025-10-14T04:15:58.242+0000] {transform.py:159} INFO - Executing fact_sales query:

    INSERT INTO gcpl-469311.datalabs_techtest.fact_sales 
        (transaction_id, customer_id, product_id, quantity, price)
    SELECT 
        t.transaction_id,
        t.customer_id,
        ti.product_id,
        ti.quantity,
        ti.price
    FROM gcpl-469311.datalabs_techtest.stg_transactions t 
    JOIN gcpl-469311.datalabs_techtest.stg_transaction_items ti ON t.transaction_id = ti.transaction_id
    WHERE NOT EXISTS (
        SELECT 1 
        FROM gcpl-469311.datalabs_techtest.fact_sales AS target
        WHERE target.transaction_id = t.transaction_id
        AND target.customer_id = t.customer_id
        AND target.product_id = ti.product_id
        AND target.quantity = ti.quantity
        AND target.price = ti.price
    );
    
[2025-10-14T04:15:58.596+0000] {transform.py:170} ERROR - General error occurred: 400 Query column 5 has type FLOAT64 which cannot be inserted into column price, which has type INT64 at [4:5]; reason: invalidQuery, location: query, message: Query column 5 has type FLOAT64 which cannot be inserted into column price, which has type INT64 at [4:5]

Location: asia-southeast2
Job ID: 556b1b41-c161-4a39-8d38-25af2244b37d
Traceback (most recent call last):
  File "/opt/airflow/dags/scripts/transform.py", line 162, in transform
    job.result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1681, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1630, in is_job_done
    raise job_failed_exception
google.api_core.exceptions.BadRequest: 400 Query column 5 has type FLOAT64 which cannot be inserted into column price, which has type INT64 at [4:5]; reason: invalidQuery, location: query, message: Query column 5 has type FLOAT64 which cannot be inserted into column price, which has type INT64 at [4:5]

Location: asia-southeast2
Job ID: 556b1b41-c161-4a39-8d38-25af2244b37d

[2025-10-14T04:15:58.603+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:15:58.615+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:15:58.616+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=transform, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T041550, end_date=20251014T041558
[2025-10-14T04:15:58.683+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:15:58.702+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:15:58.704+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:20:48.181+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:20:48.199+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:20:48.207+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:20:48.207+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:20:48.220+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:20:48.226+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=296) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:20:48.227+0000] {standard_task_runner.py:72} INFO - Started process 297 to run task
[2025-10-14T04:20:48.227+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'transform', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpzd2gc_qj']
[2025-10-14T04:20:48.228+0000] {standard_task_runner.py:105} INFO - Job 269: Subtask transform
[2025-10-14T04:20:48.279+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:20:48.355+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:20:48.356+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:20:49.067+0000] {transform.py:140} INFO - Executing dwh_ddl.sql query:
CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.fact_sales (
        transaction_id INT64,
        customer_id INT64,
        product_id INT64,
        quantity INT64,
        price FLOAT
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_customers (
        customer_id STRING,
        name STRING,
        email STRING,
        city STRING,
        signup_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_products (
        product_id INT64,
        product_name STRING,
        category STRING,
        price FLOAT64,
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_dates (
        transaction_id INT64,
        transaction_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_campaigns (
        campaign_id INT64,
        campaign_name STRING,
        start_date DATE,
        end_date DATE,
        channel STRING
    );
[2025-10-14T04:20:49.908+0000] {transform.py:170} ERROR - General error occurred: 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/gcpl-469311/queries/20f82cf8-5546-4c00-aa1a-58ac83b83b08?maxResults=0&location=asia-southeast2&prettyPrint=false: Query error: Type not found: FLOAT at [6:15]

Location: asia-southeast2
Job ID: 20f82cf8-5546-4c00-aa1a-58ac83b83b08
Traceback (most recent call last):
  File "/opt/airflow/dags/scripts/transform.py", line 144, in transform
    job.result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1681, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1650, in is_job_done
    self._reload_query_results(retry=retry, **reload_query_results_kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1448, in _reload_query_results
    self._query_results = self._client._get_query_results(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2034, in _get_query_results
    resource = self._call_api(
               ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 843, in _call_api
    return call()
           ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/gcpl-469311/queries/20f82cf8-5546-4c00-aa1a-58ac83b83b08?maxResults=0&location=asia-southeast2&prettyPrint=false: Query error: Type not found: FLOAT at [6:15]

Location: asia-southeast2
Job ID: 20f82cf8-5546-4c00-aa1a-58ac83b83b08

[2025-10-14T04:20:49.917+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:20:49.930+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:20:49.930+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=transform, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042048, end_date=20251014T042049
[2025-10-14T04:20:49.967+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:20:49.986+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:20:49.988+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:22:23.949+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:22:23.969+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:22:23.976+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:22:23.977+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:22:23.988+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:22:23.994+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=532) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:22:23.995+0000] {standard_task_runner.py:72} INFO - Started process 533 to run task
[2025-10-14T04:22:23.996+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'transform', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpp_jtyf47']
[2025-10-14T04:22:23.997+0000] {standard_task_runner.py:105} INFO - Job 329: Subtask transform
[2025-10-14T04:22:24.046+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:22:24.121+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:22:24.122+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:22:24.797+0000] {transform.py:140} INFO - Executing dwh_ddl.sql query:
CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.fact_sales (
        transaction_id INT64,
        customer_id INT64,
        product_id INT64,
        quantity INT64,
        price FLOAT64
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_customers (
        customer_id STRING,
        name STRING,
        email STRING,
        city STRING,
        signup_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_products (
        product_id INT64,
        product_name STRING,
        category STRING,
        price FLOAT64,
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_dates (
        transaction_id INT64,
        transaction_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_campaigns (
        campaign_id INT64,
        campaign_name STRING,
        start_date DATE,
        end_date DATE,
        channel STRING
    );
[2025-10-14T04:22:28.170+0000] {transform.py:148} INFO - query executed successfully.
[2025-10-14T04:22:28.171+0000] {transform.py:159} INFO - Executing fact_sales query:

    INSERT INTO gcpl-469311.datalabs_techtest.fact_sales 
        (transaction_id, customer_id, product_id, quantity, price)
    SELECT 
        t.transaction_id,
        t.customer_id,
        ti.product_id,
        ti.quantity,
        ti.price
    FROM gcpl-469311.datalabs_techtest.stg_transactions t 
    JOIN gcpl-469311.datalabs_techtest.stg_transaction_items ti ON t.transaction_id = ti.transaction_id
    WHERE NOT EXISTS (
        SELECT 1 
        FROM gcpl-469311.datalabs_techtest.fact_sales AS target
        WHERE target.transaction_id = t.transaction_id
        AND target.customer_id = t.customer_id
        AND target.product_id = ti.product_id
        AND target.quantity = ti.quantity
        AND target.price = ti.price
    );
    
[2025-10-14T04:22:30.686+0000] {transform.py:167} INFO - fact_sales query executed successfully.
[2025-10-14T04:22:30.687+0000] {transform.py:159} INFO - Executing dim_customers query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_customers AS target
    USING (
        SELECT
        c.customer_id ,
        c.name ,
        c.email ,
        c.city ,
        c.signup_date ,
    FROM gcpl-469311.datalabs_techtest.stg_customers c
    ) AS source
    ON target.customer_id = source.customer_id

    WHEN MATCHED THEN
    UPDATE SET
        target.name = source.name,
        target.email = source.email,
        target.city = source.city,
        target.signup_date = source.signup_date

    WHEN NOT MATCHED THEN
    INSERT (customer_id, name, email, city, signup_date)
    VALUES (source.customer_id, source.name, source.email, source.city, source.signup_date)
    ;
    
[2025-10-14T04:22:31.088+0000] {transform.py:170} ERROR - General error occurred: 400 No matching signature for operator = for argument types: STRING, INT64
  Signature: T1 = T1
    Unable to find common supertype for templated argument <T1>
      Input types for <T1>: {INT64, STRING} at [12:8]; reason: invalidQuery, location: query, message: No matching signature for operator = for argument types: STRING, INT64
  Signature: T1 = T1
    Unable to find common supertype for templated argument <T1>
      Input types for <T1>: {INT64, STRING} at [12:8]

Location: asia-southeast2
Job ID: 58449b0f-5a5b-43af-8e4f-240c770d4459
Traceback (most recent call last):
  File "/opt/airflow/dags/scripts/transform.py", line 162, in transform
    job.result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1681, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1630, in is_job_done
    raise job_failed_exception
google.api_core.exceptions.BadRequest: 400 No matching signature for operator = for argument types: STRING, INT64
  Signature: T1 = T1
    Unable to find common supertype for templated argument <T1>
      Input types for <T1>: {INT64, STRING} at [12:8]; reason: invalidQuery, location: query, message: No matching signature for operator = for argument types: STRING, INT64
  Signature: T1 = T1
    Unable to find common supertype for templated argument <T1>
      Input types for <T1>: {INT64, STRING} at [12:8]

Location: asia-southeast2
Job ID: 58449b0f-5a5b-43af-8e4f-240c770d4459

[2025-10-14T04:22:31.095+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:22:31.108+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:22:31.108+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=transform, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042223, end_date=20251014T042231
[2025-10-14T04:22:31.170+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:22:31.186+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:22:31.188+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:26:17.292+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:26:17.313+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:26:17.323+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:26:17.324+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:26:17.336+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:26:17.344+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:26:17.346+0000] {standard_task_runner.py:72} INFO - Started process 668 to run task
[2025-10-14T04:26:17.347+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'transform', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '353', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmprmq6cipk']
[2025-10-14T04:26:17.348+0000] {standard_task_runner.py:105} INFO - Job 353: Subtask transform
[2025-10-14T04:26:17.413+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:26:17.493+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:26:17.494+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:26:18.231+0000] {transform.py:140} INFO - Executing dwh_ddl.sql query:
CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.fact_sales (
        transaction_id INT64,
        customer_id INT64,
        product_id INT64,
        quantity INT64,
        price FLOAT64
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_customers (
        customer_id INT64,
        name STRING,
        email STRING,
        city STRING,
        signup_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_products (
        product_id INT64,
        product_name STRING,
        category STRING,
        price FLOAT64,
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_dates (
        transaction_id INT64,
        transaction_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_campaigns (
        campaign_id INT64,
        campaign_name STRING,
        start_date DATE,
        end_date DATE,
        channel STRING
    );
[2025-10-14T04:26:21.661+0000] {transform.py:148} INFO - query executed successfully.
[2025-10-14T04:26:21.662+0000] {transform.py:159} INFO - Executing fact_sales query:

    INSERT INTO gcpl-469311.datalabs_techtest.fact_sales 
        (transaction_id, customer_id, product_id, quantity, price)
    SELECT 
        t.transaction_id,
        t.customer_id,
        ti.product_id,
        ti.quantity,
        ti.price
    FROM gcpl-469311.datalabs_techtest.stg_transactions t 
    JOIN gcpl-469311.datalabs_techtest.stg_transaction_items ti ON t.transaction_id = ti.transaction_id
    WHERE NOT EXISTS (
        SELECT 1 
        FROM gcpl-469311.datalabs_techtest.fact_sales AS target
        WHERE target.transaction_id = t.transaction_id
        AND target.customer_id = t.customer_id
        AND target.product_id = ti.product_id
        AND target.quantity = ti.quantity
        AND target.price = ti.price
    );
    
[2025-10-14T04:26:23.349+0000] {transform.py:167} INFO - fact_sales query executed successfully.
[2025-10-14T04:26:23.350+0000] {transform.py:159} INFO - Executing dim_customers query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_customers AS target
    USING (
        SELECT
        c.customer_id ,
        c.name ,
        c.email ,
        c.city ,
        c.signup_date ,
    FROM gcpl-469311.datalabs_techtest.stg_customers c
    ) AS source
    ON target.customer_id = source.customer_id

    WHEN MATCHED THEN
    UPDATE SET
        target.name = source.name,
        target.email = source.email,
        target.city = source.city,
        target.signup_date = source.signup_date

    WHEN NOT MATCHED THEN
    INSERT (customer_id, name, email, city, signup_date)
    VALUES (source.customer_id, source.name, source.email, source.city, source.signup_date)
    ;
    
[2025-10-14T04:26:25.093+0000] {transform.py:167} INFO - dim_customers query executed successfully.
[2025-10-14T04:26:25.094+0000] {transform.py:159} INFO - Executing dim_products query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_products AS target
    USING (
        SELECT
            p.product_id ,
            p.product_name ,
            p.category ,
            p.price
        FROM gcpl-469311.datalabs_techtest.stg_products p
    ) AS source
    ON target.product_id = source.product_id

    WHEN MATCHED THEN
    UPDATE SET
        target.product_name = source.product_name,
        target.category = source.category,
        target.price = source.price

    WHEN NOT MATCHED THEN
    INSERT (product_id, product_name, category, price)
    VALUES (source.product_id, source.product_name, source.category, source.price)
    ;
    
[2025-10-14T04:26:26.839+0000] {transform.py:167} INFO - dim_products query executed successfully.
[2025-10-14T04:26:26.840+0000] {transform.py:159} INFO - Executing dim_dates query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_date AS target
    USING (
        SELECT
            t.transaction_id ,
            t.transaction_date
        FROM gcpl-469311.datalabs_techtest.stg_transactions t
    ) AS source
    ON target.transaction_id = source.transaction_id

    WHEN MATCHED THEN
    UPDATE SET
        target.transaction_date = source.transaction_date

    WHEN NOT MATCHED THEN
    INSERT (transaction_id, transaction_date)
    VALUES (source.transaction_id, source.transaction_date);
    
[2025-10-14T04:26:27.076+0000] {transform.py:170} ERROR - General error occurred: 404 Not found: Table gcpl-469311:datalabs_techtest.dim_date was not found in location asia-southeast2; reason: notFound, message: Not found: Table gcpl-469311:datalabs_techtest.dim_date was not found in location asia-southeast2

Location: asia-southeast2
Job ID: e180b33e-9769-4f48-be94-e22975e2db79
Traceback (most recent call last):
  File "/opt/airflow/dags/scripts/transform.py", line 162, in transform
    job.result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1681, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1630, in is_job_done
    raise job_failed_exception
google.api_core.exceptions.NotFound: 404 Not found: Table gcpl-469311:datalabs_techtest.dim_date was not found in location asia-southeast2; reason: notFound, message: Not found: Table gcpl-469311:datalabs_techtest.dim_date was not found in location asia-southeast2

Location: asia-southeast2
Job ID: e180b33e-9769-4f48-be94-e22975e2db79

[2025-10-14T04:26:27.083+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:26:27.094+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:26:27.095+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=transform, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042617, end_date=20251014T042627
[2025-10-14T04:26:27.130+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:26:27.146+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:26:27.148+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:28:20.109+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:28:20.128+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:28:20.137+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:28:20.137+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:28:20.150+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:28:20.157+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=781) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:28:20.158+0000] {standard_task_runner.py:72} INFO - Started process 782 to run task
[2025-10-14T04:28:20.158+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'transform', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '377', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpk_jauxuc']
[2025-10-14T04:28:20.159+0000] {standard_task_runner.py:105} INFO - Job 377: Subtask transform
[2025-10-14T04:28:20.209+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:28:20.281+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:28:20.282+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:28:20.996+0000] {transform.py:140} INFO - Executing dwh_ddl.sql query:
CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.fact_sales (
        transaction_id INT64,
        customer_id INT64,
        product_id INT64,
        quantity INT64,
        price FLOAT64
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_customers (
        customer_id INT64,
        name STRING,
        email STRING,
        city STRING,
        signup_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_products (
        product_id INT64,
        product_name STRING,
        category STRING,
        price FLOAT64,
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_dates (
        transaction_id INT64,
        transaction_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_campaigns (
        campaign_id INT64,
        campaign_name STRING,
        start_date DATE,
        end_date DATE,
        channel STRING
    );
[2025-10-14T04:28:24.333+0000] {transform.py:148} INFO - query executed successfully.
[2025-10-14T04:28:24.334+0000] {transform.py:159} INFO - Executing fact_sales query:

    INSERT INTO gcpl-469311.datalabs_techtest.fact_sales 
        (transaction_id, customer_id, product_id, quantity, price)
    SELECT 
        t.transaction_id,
        t.customer_id,
        ti.product_id,
        ti.quantity,
        ti.price
    FROM gcpl-469311.datalabs_techtest.stg_transactions t 
    JOIN gcpl-469311.datalabs_techtest.stg_transaction_items ti ON t.transaction_id = ti.transaction_id
    WHERE NOT EXISTS (
        SELECT 1 
        FROM gcpl-469311.datalabs_techtest.fact_sales AS target
        WHERE target.transaction_id = t.transaction_id
        AND target.customer_id = t.customer_id
        AND target.product_id = ti.product_id
        AND target.quantity = ti.quantity
        AND target.price = ti.price
    );
    
[2025-10-14T04:28:26.140+0000] {transform.py:167} INFO - fact_sales query executed successfully.
[2025-10-14T04:28:26.140+0000] {transform.py:159} INFO - Executing dim_customers query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_customers AS target
    USING (
        SELECT
        c.customer_id ,
        c.name ,
        c.email ,
        c.city ,
        c.signup_date ,
    FROM gcpl-469311.datalabs_techtest.stg_customers c
    ) AS source
    ON target.customer_id = source.customer_id

    WHEN MATCHED THEN
    UPDATE SET
        target.name = source.name,
        target.email = source.email,
        target.city = source.city,
        target.signup_date = source.signup_date

    WHEN NOT MATCHED THEN
    INSERT (customer_id, name, email, city, signup_date)
    VALUES (source.customer_id, source.name, source.email, source.city, source.signup_date)
    ;
    
[2025-10-14T04:28:27.940+0000] {transform.py:167} INFO - dim_customers query executed successfully.
[2025-10-14T04:28:27.941+0000] {transform.py:159} INFO - Executing dim_products query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_products AS target
    USING (
        SELECT
            p.product_id ,
            p.product_name ,
            p.category ,
            p.price
        FROM gcpl-469311.datalabs_techtest.stg_products p
    ) AS source
    ON target.product_id = source.product_id

    WHEN MATCHED THEN
    UPDATE SET
        target.product_name = source.product_name,
        target.category = source.category,
        target.price = source.price

    WHEN NOT MATCHED THEN
    INSERT (product_id, product_name, category, price)
    VALUES (source.product_id, source.product_name, source.category, source.price)
    ;
    
[2025-10-14T04:28:29.661+0000] {transform.py:167} INFO - dim_products query executed successfully.
[2025-10-14T04:28:29.662+0000] {transform.py:159} INFO - Executing dim_dates query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_dates AS target
    USING (
        SELECT
            t.transaction_id ,
            t.transaction_date
        FROM gcpl-469311.datalabs_techtest.stg_transactions t
    ) AS source
    ON target.transaction_id = source.transaction_id

    WHEN MATCHED THEN
    UPDATE SET
        target.transaction_date = source.transaction_date

    WHEN NOT MATCHED THEN
    INSERT (transaction_id, transaction_date)
    VALUES (source.transaction_id, source.transaction_date);
    
[2025-10-14T04:28:31.934+0000] {transform.py:167} INFO - dim_dates query executed successfully.
[2025-10-14T04:28:31.935+0000] {transform.py:159} INFO - Executing dim_campaigns query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_campaigns AS target
    USING (
        SELECT
            mc.campaign_id ,
            mc.campaign_name ,
            mc.start_date ,
            mc.end_date ,
            mc.channel
        FROM gcpl-469311.datalabs_techtest.stg_marketing_campaigns mc
    ) AS source

    ON target.campaign_id = source.campaign_id

    WHEN MATCHED THEN
    UPDATE SET
        target.campaign_name = source.campaign_name ,
        target.start_date = source.start_date ,
        target.end_date = source.end_date ,
        target.channel = source.channel

    WHEN NOT MATCHED THEN
    INSERT (campaign_id, campaign_name, start_date, end_date, channel)
    VALUES (source.campaign_id, source.campaign_name, source.start_date, source.end_date, source.channel);
    
[2025-10-14T04:28:33.624+0000] {transform.py:167} INFO - dim_campaigns query executed successfully.
[2025-10-14T04:28:33.624+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:28:33.636+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:28:33.636+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=transform, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T042820, end_date=20251014T042833
[2025-10-14T04:28:33.682+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:28:33.700+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:28:33.702+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:31:27.914+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:31:27.934+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:31:27.943+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-10-14T04:31:27.944+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:31:27.956+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2025-09-01 00:00:00+00:00
[2025-10-14T04:31:27.963+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1074) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:31:27.964+0000] {standard_task_runner.py:72} INFO - Started process 1075 to run task
[2025-10-14T04:31:27.964+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'transform', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '449', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpoosirpcn']
[2025-10-14T04:31:27.965+0000] {standard_task_runner.py:105} INFO - Job 449: Subtask transform
[2025-10-14T04:31:28.014+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.transform scheduled__2025-09-01T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:31:28.086+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-10-14T04:31:28.087+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:31:28.774+0000] {transform.py:140} INFO - Executing dwh_ddl.sql query:
CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.fact_sales (
        transaction_id INT64,
        customer_id INT64,
        product_id INT64,
        quantity INT64,
        price FLOAT64
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_customers (
        customer_id INT64,
        name STRING,
        email STRING,
        city STRING,
        signup_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_products (
        product_id INT64,
        product_name STRING,
        category STRING,
        price FLOAT64,
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_dates (
        transaction_id INT64,
        transaction_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_campaigns (
        campaign_id INT64,
        campaign_name STRING,
        start_date DATE,
        end_date DATE,
        channel STRING
    );
[2025-10-14T04:31:31.420+0000] {transform.py:148} INFO - query executed successfully.
[2025-10-14T04:31:31.420+0000] {transform.py:159} INFO - Executing fact_sales query:

    INSERT INTO gcpl-469311.datalabs_techtest.fact_sales 
        (transaction_id, customer_id, product_id, quantity, price)
    SELECT 
        t.transaction_id,
        t.customer_id,
        ti.product_id,
        ti.quantity,
        ti.price
    FROM gcpl-469311.datalabs_techtest.stg_transactions t 
    JOIN gcpl-469311.datalabs_techtest.stg_transaction_items ti ON t.transaction_id = ti.transaction_id
    WHERE NOT EXISTS (
        SELECT 1 
        FROM gcpl-469311.datalabs_techtest.fact_sales AS target
        WHERE target.transaction_id = t.transaction_id
        AND target.customer_id = t.customer_id
        AND target.product_id = ti.product_id
        AND target.quantity = ti.quantity
        AND target.price = ti.price
    );
    
[2025-10-14T04:31:33.108+0000] {transform.py:167} INFO - fact_sales query executed successfully.
[2025-10-14T04:31:33.109+0000] {transform.py:159} INFO - Executing dim_customers query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_customers AS target
    USING (
        SELECT
        c.customer_id ,
        c.name ,
        c.email ,
        c.city ,
        c.signup_date ,
    FROM gcpl-469311.datalabs_techtest.stg_customers c
    ) AS source
    ON target.customer_id = source.customer_id

    WHEN MATCHED THEN
    UPDATE SET
        target.name = source.name,
        target.email = source.email,
        target.city = source.city,
        target.signup_date = source.signup_date

    WHEN NOT MATCHED THEN
    INSERT (customer_id, name, email, city, signup_date)
    VALUES (source.customer_id, source.name, source.email, source.city, source.signup_date)
    ;
    
[2025-10-14T04:31:34.850+0000] {transform.py:167} INFO - dim_customers query executed successfully.
[2025-10-14T04:31:34.851+0000] {transform.py:159} INFO - Executing dim_products query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_products AS target
    USING (
        SELECT
            p.product_id ,
            p.product_name ,
            p.category ,
            p.price
        FROM gcpl-469311.datalabs_techtest.stg_products p
    ) AS source
    ON target.product_id = source.product_id

    WHEN MATCHED THEN
    UPDATE SET
        target.product_name = source.product_name,
        target.category = source.category,
        target.price = source.price

    WHEN NOT MATCHED THEN
    INSERT (product_id, product_name, category, price)
    VALUES (source.product_id, source.product_name, source.category, source.price)
    ;
    
[2025-10-14T04:31:36.508+0000] {transform.py:167} INFO - dim_products query executed successfully.
[2025-10-14T04:31:36.508+0000] {transform.py:159} INFO - Executing dim_dates query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_dates AS target
    USING (
        SELECT
            t.transaction_id ,
            t.transaction_date
        FROM gcpl-469311.datalabs_techtest.stg_transactions t
    ) AS source
    ON target.transaction_id = source.transaction_id

    WHEN MATCHED THEN
    UPDATE SET
        target.transaction_date = source.transaction_date

    WHEN NOT MATCHED THEN
    INSERT (transaction_id, transaction_date)
    VALUES (source.transaction_id, source.transaction_date);
    
[2025-10-14T04:31:38.220+0000] {transform.py:167} INFO - dim_dates query executed successfully.
[2025-10-14T04:31:38.221+0000] {transform.py:159} INFO - Executing dim_campaigns query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_campaigns AS target
    USING (
        SELECT
            mc.campaign_id ,
            mc.campaign_name ,
            mc.start_date ,
            mc.end_date ,
            mc.channel
        FROM gcpl-469311.datalabs_techtest.stg_marketing_campaigns mc
    ) AS source

    ON target.campaign_id = source.campaign_id

    WHEN MATCHED THEN
    UPDATE SET
        target.campaign_name = source.campaign_name ,
        target.start_date = source.start_date ,
        target.end_date = source.end_date ,
        target.channel = source.channel

    WHEN NOT MATCHED THEN
    INSERT (campaign_id, campaign_name, start_date, end_date, channel)
    VALUES (source.campaign_id, source.campaign_name, source.start_date, source.end_date, source.channel);
    
[2025-10-14T04:31:40.002+0000] {transform.py:167} INFO - dim_campaigns query executed successfully.
[2025-10-14T04:31:40.002+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:31:40.014+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:31:40.014+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=transform, run_id=scheduled__2025-09-01T00:00:00+00:00, execution_date=20250901T000000, start_date=20251014T043127, end_date=20251014T043140
[2025-10-14T04:31:40.065+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:31:40.083+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:31:40.085+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
