[2025-10-13T08:37:07.782+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:37:07.810+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:37:07.821+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:37:07.822+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:37:07.840+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-02 00:00:00+00:00
[2025-10-13T08:37:07.849+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=230) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:37:07.851+0000] {standard_task_runner.py:72} INFO - Started process 231 to run task
[2025-10-13T08:37:07.851+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpaxzmt99u']
[2025-10-13T08:37:07.852+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask extract_load_group.load_customers
[2025-10-13T08:37:07.939+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:37:08.054+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T08:37:08.056+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:37:10.912+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:10.932+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T083707, end_date=20251013T083710
[2025-10-13T08:37:10.950+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:37:10.950+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 29 for task extract_load_group.load_customers (403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.; 231)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:10.999+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-13T08:37:11.029+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:37:11.033+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:54:52.002+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:54:52.031+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:54:52.043+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T08:54:52.044+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:54:52.061+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-02 00:00:00+00:00
[2025-10-13T08:54:52.071+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=773) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:54:52.074+0000] {standard_task_runner.py:72} INFO - Started process 779 to run task
[2025-10-13T08:54:52.074+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp5pjzcmmc']
[2025-10-13T08:54:52.075+0000] {standard_task_runner.py:105} INFO - Job 120: Subtask extract_load_group.load_customers
[2025-10-13T08:54:52.146+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:54:52.266+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T08:54:52.267+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:55:04.905+0000] {load.py:30} INFO - Loaded 0 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-13T08:55:04.906+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:55:04.920+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:55:04.921+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T085452, end_date=20251013T085504
[2025-10-13T08:55:04.955+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:55:04.977+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:55:04.979+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:20:51.751+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:20:51.772+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T09:20:51.782+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-13T09:20:51.782+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:20:51.796+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-02 00:00:00+00:00
[2025-10-13T09:20:51.804+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1332) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:20:51.806+0000] {standard_task_runner.py:72} INFO - Started process 1334 to run task
[2025-10-13T09:20:51.806+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp898g34a1']
[2025-10-13T09:20:51.807+0000] {standard_task_runner.py:105} INFO - Job 182: Subtask extract_load_group.load_customers
[2025-10-13T09:20:51.876+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:20:51.979+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-13T09:20:51.980+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:21:01.561+0000] {load.py:30} INFO - Loaded 27 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-13T09:21:01.562+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:21:01.573+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:21:01.574+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251013T092051, end_date=20251013T092101
[2025-10-13T09:21:01.621+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:21:01.643+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:21:01.645+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:16:04.354+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:16:04.379+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:16:04.390+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:16:04.391+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:16:04.406+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:16:04.414+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=173) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:16:04.416+0000] {standard_task_runner.py:72} INFO - Started process 178 to run task
[2025-10-14T04:16:04.416+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpxwkt9qqf']
[2025-10-14T04:16:04.418+0000] {standard_task_runner.py:105} INFO - Job 254: Subtask extract_load_group.load_customers
[2025-10-14T04:16:04.480+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:16:04.590+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:16:04.591+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:16:09.880+0000] {load.py:30} INFO - Loaded 27 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-14T04:16:09.881+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:16:09.893+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:16:09.893+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T041604, end_date=20251014T041609
[2025-10-14T04:16:09.936+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:16:09.957+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:16:09.959+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:20:54.516+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:20:54.540+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:20:54.550+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:20:54.551+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:20:54.570+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:20:54.578+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=317) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:20:54.580+0000] {standard_task_runner.py:72} INFO - Started process 322 to run task
[2025-10-14T04:20:54.585+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpa7in4g52']
[2025-10-14T04:20:54.587+0000] {standard_task_runner.py:105} INFO - Job 275: Subtask extract_load_group.load_customers
[2025-10-14T04:20:54.664+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:20:54.778+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:20:54.780+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:20:59.424+0000] {load.py:30} INFO - Loaded 27 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-14T04:20:59.425+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:20:59.437+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:20:59.438+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042054, end_date=20251014T042059
[2025-10-14T04:20:59.492+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:20:59.520+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:20:59.522+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:22:35.782+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:22:35.803+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:22:35.811+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:22:35.812+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:22:35.826+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:22:35.835+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=554) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:22:35.836+0000] {standard_task_runner.py:72} INFO - Started process 564 to run task
[2025-10-14T04:22:35.837+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpc2sjhxix']
[2025-10-14T04:22:35.838+0000] {standard_task_runner.py:105} INFO - Job 339: Subtask extract_load_group.load_customers
[2025-10-14T04:22:35.894+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:22:35.984+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:22:35.985+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:22:41.378+0000] {load.py:30} INFO - Loaded 27 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-14T04:22:41.379+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:22:41.389+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:22:41.390+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042235, end_date=20251014T042241
[2025-10-14T04:22:41.431+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:22:41.455+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:22:41.458+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:26:32.576+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:26:32.601+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:26:32.613+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:26:32.614+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:26:32.631+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:26:32.640+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=686) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:26:32.642+0000] {standard_task_runner.py:72} INFO - Started process 697 to run task
[2025-10-14T04:26:32.643+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '362', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpx3__fugi']
[2025-10-14T04:26:32.644+0000] {standard_task_runner.py:105} INFO - Job 362: Subtask extract_load_group.load_customers
[2025-10-14T04:26:32.708+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:26:32.813+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:26:32.814+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:26:36.901+0000] {load.py:30} INFO - Loaded 27 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-14T04:26:36.902+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:26:36.914+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:26:36.915+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042632, end_date=20251014T042636
[2025-10-14T04:26:36.954+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:26:36.979+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:26:36.981+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:28:38.247+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:28:38.278+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:28:38.291+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:28:38.292+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:28:38.315+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:28:38.327+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=802) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:28:38.330+0000] {standard_task_runner.py:72} INFO - Started process 812 to run task
[2025-10-14T04:28:38.333+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '387', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmph0x45zvg']
[2025-10-14T04:28:38.334+0000] {standard_task_runner.py:105} INFO - Job 387: Subtask extract_load_group.load_customers
[2025-10-14T04:28:38.409+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:28:38.541+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:28:38.543+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:28:43.127+0000] {load.py:30} INFO - Loaded 27 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-14T04:28:43.128+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:28:43.142+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:28:43.143+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T042838, end_date=20251014T042843
[2025-10-14T04:28:43.202+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:28:43.215+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:35:32.786+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:35:32.808+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:35:32.819+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [queued]>
[2025-10-14T04:35:32.819+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:35:32.838+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_customers> on 2025-09-02 00:00:00+00:00
[2025-10-14T04:35:32.846+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1149) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:35:32.849+0000] {standard_task_runner.py:72} INFO - Started process 1157 to run task
[2025-10-14T04:35:32.849+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_customers', 'scheduled__2025-09-02T00:00:00+00:00', '--job-id', '458', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpg07hkuj6']
[2025-10-14T04:35:32.850+0000] {standard_task_runner.py:105} INFO - Job 458: Subtask extract_load_group.load_customers
[2025-10-14T04:35:32.933+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_customers scheduled__2025-09-02T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:35:33.049+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T00:00:00+00:00'
[2025-10-14T04:35:33.050+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:35:39.626+0000] {load.py:30} INFO - Loaded 27 rows and 5 columns to gcpl-469311.datalabs_techtest.stg_customers
[2025-10-14T04:35:39.627+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:35:39.638+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:35:39.639+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_customers, run_id=scheduled__2025-09-02T00:00:00+00:00, execution_date=20250902T000000, start_date=20251014T043532, end_date=20251014T043539
[2025-10-14T04:35:39.700+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:35:39.725+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:35:39.727+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
