[2025-10-13T08:37:15.210+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:37:15.242+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T08:37:15.252+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T08:37:15.253+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:37:15.270+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-03 00:00:00+00:00
[2025-10-13T08:37:15.280+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:37:15.282+0000] {standard_task_runner.py:72} INFO - Started process 269 to run task
[2025-10-13T08:37:15.282+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpmjve7o3c']
[2025-10-13T08:37:15.284+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask extract_load_group.load_products
[2025-10-13T08:37:15.350+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:37:15.460+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-13T08:37:15.461+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:37:18.213+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:18.230+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251013T083715, end_date=20251013T083718
[2025-10-13T08:37:18.246+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:37:18.247+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 42 for task extract_load_group.load_products (403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.; 269)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:18.309+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-13T08:37:18.321+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:55:12.029+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:55:12.049+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T08:55:12.058+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T08:55:12.059+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:55:12.074+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-03 00:00:00+00:00
[2025-10-13T08:55:12.082+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=809) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:55:12.084+0000] {standard_task_runner.py:72} INFO - Started process 813 to run task
[2025-10-13T08:55:12.084+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp3cvae7z7']
[2025-10-13T08:55:12.085+0000] {standard_task_runner.py:105} INFO - Job 129: Subtask extract_load_group.load_products
[2025-10-13T08:55:12.144+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:55:12.236+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-13T08:55:12.238+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:55:24.654+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-13T08:55:24.655+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:55:24.667+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:55:24.668+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251013T085512, end_date=20251013T085524
[2025-10-13T08:55:24.709+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:55:24.730+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:55:24.732+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:21:10.663+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:21:10.684+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T09:21:10.694+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T09:21:10.694+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:21:10.709+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-03 00:00:00+00:00
[2025-10-13T09:21:10.717+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1375) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:21:10.718+0000] {standard_task_runner.py:72} INFO - Started process 1383 to run task
[2025-10-13T09:21:10.718+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpduxudmls']
[2025-10-13T09:21:10.720+0000] {standard_task_runner.py:105} INFO - Job 192: Subtask extract_load_group.load_products
[2025-10-13T09:21:10.780+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:21:10.881+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-13T09:21:10.883+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:21:21.785+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-13T09:21:21.785+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:21:21.800+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:21:21.801+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251013T092110, end_date=20251013T092121
[2025-10-13T09:21:21.863+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:21:21.888+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:21:21.890+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:21:09.790+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:21:09.820+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:21:09.837+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:21:09.839+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:21:09.866+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-03 00:00:00+00:00
[2025-10-14T04:21:09.875+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=361) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:21:09.878+0000] {standard_task_runner.py:72} INFO - Started process 363 to run task
[2025-10-14T04:21:09.878+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '289', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpgyxqrsjq']
[2025-10-14T04:21:09.881+0000] {standard_task_runner.py:105} INFO - Job 289: Subtask extract_load_group.load_products
[2025-10-14T04:21:09.965+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:21:10.084+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-14T04:21:10.086+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:21:16.497+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-14T04:21:16.498+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:21:16.510+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:21:16.511+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251014T042109, end_date=20251014T042116
[2025-10-14T04:21:16.563+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:21:16.585+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:21:16.587+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:29:04.140+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:29:04.163+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:29:04.175+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:29:04.175+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:29:04.191+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-03 00:00:00+00:00
[2025-10-14T04:29:04.199+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=853) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:29:04.201+0000] {standard_task_runner.py:72} INFO - Started process 856 to run task
[2025-10-14T04:29:04.202+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '399', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpayeihqza']
[2025-10-14T04:29:04.203+0000] {standard_task_runner.py:105} INFO - Job 399: Subtask extract_load_group.load_products
[2025-10-14T04:29:04.273+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:29:04.383+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-14T04:29:04.384+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:29:08.977+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-14T04:29:08.978+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:29:08.993+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:29:08.993+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251014T042904, end_date=20251014T042908
[2025-10-14T04:29:09.037+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:29:09.065+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:29:09.067+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:35:59.231+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:35:59.256+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:35:59.267+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:35:59.267+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:35:59.285+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_products> on 2025-09-03 00:00:00+00:00
[2025-10-14T04:35:59.293+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1199) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:35:59.295+0000] {standard_task_runner.py:72} INFO - Started process 1205 to run task
[2025-10-14T04:35:59.295+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_products', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '467', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp2abld7p8']
[2025-10-14T04:35:59.297+0000] {standard_task_runner.py:105} INFO - Job 467: Subtask extract_load_group.load_products
[2025-10-14T04:35:59.374+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_products scheduled__2025-09-03T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:35:59.500+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_products' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-14T04:35:59.502+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:36:04.705+0000] {load.py:30} INFO - Loaded 1000 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_products
[2025-10-14T04:36:04.707+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:36:04.721+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:36:04.722+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_products, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251014T043559, end_date=20251014T043604
[2025-10-14T04:36:04.778+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:36:04.802+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:36:04.804+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
