[2025-10-13T08:37:15.210+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:37:15.242+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T08:37:15.252+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T08:37:15.253+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:37:15.269+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-03 00:00:00+00:00
[2025-10-13T08:37:15.278+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=264) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:37:15.280+0000] {standard_task_runner.py:72} INFO - Started process 267 to run task
[2025-10-13T08:37:15.280+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpssqpuwhm']
[2025-10-13T08:37:15.282+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask extract_load_group.load_transactions
[2025-10-13T08:37:15.348+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:37:15.464+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-13T08:37:15.466+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:37:18.213+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:18.229+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251013T083715, end_date=20251013T083718
[2025-10-13T08:37:18.245+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:37:18.246+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 41 for task extract_load_group.load_transactions (403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.; 267)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2599, in load_table_from_file
    response = self._do_resumable_upload(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3019, in _do_resumable_upload
    upload, transport = self._initiate_resumable_upload(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 3088, in _initiate_resumable_upload
    upload.initiate(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 420, in initiate
    return _request_helpers.wait_and_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
               ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/requests/upload.py", line 416, in retriable_request
    self._process_initiate_response(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_upload.py", line 518, in _process_initiate_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 403, 'Expected one of', 200, 201)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/load.py", line 22, in load
    job = client.load_table_from_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 2607, in load_table_from_file
    raise exceptions.from_http_response(exc.response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/gcpl-469311/jobs?uploadType=resumable: Access Denied: Project gcpl-469311: User does not have bigquery.jobs.create permission in project gcpl-469311.
[2025-10-13T08:37:18.309+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-13T08:37:18.321+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T08:55:12.030+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T08:55:12.051+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T08:55:12.059+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T08:55:12.060+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T08:55:12.076+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-03 00:00:00+00:00
[2025-10-13T08:55:12.083+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=808) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T08:55:12.085+0000] {standard_task_runner.py:72} INFO - Started process 814 to run task
[2025-10-13T08:55:12.085+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp39c6k69a']
[2025-10-13T08:55:12.087+0000] {standard_task_runner.py:105} INFO - Job 131: Subtask extract_load_group.load_transactions
[2025-10-13T08:55:12.144+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T08:55:12.237+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-13T08:55:12.239+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T08:55:23.085+0000] {load.py:30} INFO - Loaded 27 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-13T08:55:23.086+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T08:55:23.097+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T08:55:23.097+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251013T085512, end_date=20251013T085523
[2025-10-13T08:55:23.142+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T08:55:23.163+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T08:55:23.165+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-13T09:21:10.653+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-13T09:21:10.676+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T09:21:10.687+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-13T09:21:10.687+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-13T09:21:10.701+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-03 00:00:00+00:00
[2025-10-13T09:21:10.708+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1377) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-13T09:21:10.710+0000] {standard_task_runner.py:72} INFO - Started process 1380 to run task
[2025-10-13T09:21:10.711+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpu_8lrqrb']
[2025-10-13T09:21:10.712+0000] {standard_task_runner.py:105} INFO - Job 191: Subtask extract_load_group.load_transactions
[2025-10-13T09:21:10.773+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [running]> on host 84d5a327cf64
[2025-10-13T09:21:10.873+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-13T09:21:10.874+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-13T09:21:21.063+0000] {load.py:30} INFO - Loaded 27 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-13T09:21:21.064+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-13T09:21:21.075+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-13T09:21:21.075+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251013T092110, end_date=20251013T092121
[2025-10-13T09:21:21.141+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-13T09:21:21.168+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-13T09:21:21.171+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:21:09.789+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:21:09.820+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:21:09.837+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:21:09.839+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:21:09.867+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-03 00:00:00+00:00
[2025-10-14T04:21:09.877+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=362) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:21:09.880+0000] {standard_task_runner.py:72} INFO - Started process 366 to run task
[2025-10-14T04:21:09.880+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmplnak3suo']
[2025-10-14T04:21:09.883+0000] {standard_task_runner.py:105} INFO - Job 290: Subtask extract_load_group.load_transactions
[2025-10-14T04:21:09.965+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:21:10.083+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-14T04:21:10.084+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:21:16.083+0000] {load.py:30} INFO - Loaded 27 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:21:16.083+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:21:16.095+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:21:16.096+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251014T042109, end_date=20251014T042116
[2025-10-14T04:21:16.160+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:21:16.183+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:21:16.185+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:29:04.140+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:29:04.164+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:29:04.174+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:29:04.174+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:29:04.191+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-03 00:00:00+00:00
[2025-10-14T04:29:04.199+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=852) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:29:04.201+0000] {standard_task_runner.py:72} INFO - Started process 858 to run task
[2025-10-14T04:29:04.204+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '398', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp56cv1a7g']
[2025-10-14T04:29:04.205+0000] {standard_task_runner.py:105} INFO - Job 398: Subtask extract_load_group.load_transactions
[2025-10-14T04:29:04.279+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:29:04.384+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-14T04:29:04.386+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:29:08.361+0000] {load.py:30} INFO - Loaded 27 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:29:08.362+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:29:08.376+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:29:08.377+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251014T042904, end_date=20251014T042908
[2025-10-14T04:29:08.435+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:29:08.467+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:29:08.469+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-10-14T04:35:59.250+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:35:59.273+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:35:59.283+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [queued]>
[2025-10-14T04:35:59.283+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:35:59.305+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_load_group.load_transactions> on 2025-09-03 00:00:00+00:00
[2025-10-14T04:35:59.314+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1202) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:35:59.317+0000] {standard_task_runner.py:72} INFO - Started process 1212 to run task
[2025-10-14T04:35:59.318+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'extract_load_group.load_transactions', 'scheduled__2025-09-03T00:00:00+00:00', '--job-id', '471', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpdv9oelnz']
[2025-10-14T04:35:59.319+0000] {standard_task_runner.py:105} INFO - Job 471: Subtask extract_load_group.load_transactions
[2025-10-14T04:35:59.395+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.extract_load_group.load_transactions scheduled__2025-09-03T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:35:59.520+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='extract_load_group.load_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-03T00:00:00+00:00'
[2025-10-14T04:35:59.521+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:36:03.714+0000] {load.py:30} INFO - Loaded 27 rows and 4 columns to gcpl-469311.datalabs_techtest.stg_transactions
[2025-10-14T04:36:03.715+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:36:03.727+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:36:03.728+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=extract_load_group.load_transactions, run_id=scheduled__2025-09-03T00:00:00+00:00, execution_date=20250903T000000, start_date=20251014T043559, end_date=20251014T043603
[2025-10-14T04:36:03.790+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:36:03.826+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:36:03.828+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
