[2025-10-14T04:42:05.472+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-14T04:42:05.490+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-14T00:00:00+00:00 [queued]>
[2025-10-14T04:42:05.498+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt-pipeline.transform scheduled__2025-09-14T00:00:00+00:00 [queued]>
[2025-10-14T04:42:05.499+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-10-14T04:42:05.512+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform> on 2025-09-14 00:00:00+00:00
[2025-10-14T04:42:05.519+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1773) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-14T04:42:05.520+0000] {standard_task_runner.py:72} INFO - Started process 1774 to run task
[2025-10-14T04:42:05.520+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'elt-pipeline', 'transform', 'scheduled__2025-09-14T00:00:00+00:00', '--job-id', '605', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp55nnz3h6']
[2025-10-14T04:42:05.521+0000] {standard_task_runner.py:105} INFO - Job 605: Subtask transform
[2025-10-14T04:42:05.568+0000] {task_command.py:467} INFO - Running <TaskInstance: elt-pipeline.transform scheduled__2025-09-14T00:00:00+00:00 [running]> on host e348b991e0be
[2025-10-14T04:42:05.656+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt-pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-14T00:00:00+00:00'
[2025-10-14T04:42:05.657+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-14T04:42:06.359+0000] {transform.py:140} INFO - Executing dwh_ddl.sql query:
CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.fact_sales (
        transaction_id INT64,
        customer_id INT64,
        product_id INT64,
        quantity INT64,
        price FLOAT64
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_customers (
        customer_id INT64,
        name STRING,
        email STRING,
        city STRING,
        signup_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_products (
        product_id INT64,
        product_name STRING,
        category STRING,
        price FLOAT64,
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_dates (
        transaction_id INT64,
        transaction_date DATE
    );

CREATE TABLE IF NOT EXISTS gcpl-469311.datalabs_techtest.dim_campaigns (
        campaign_id INT64,
        campaign_name STRING,
        start_date DATE,
        end_date DATE,
        channel STRING
    );
[2025-10-14T04:42:10.995+0000] {transform.py:148} INFO - query executed successfully.
[2025-10-14T04:42:10.996+0000] {transform.py:159} INFO - Executing fact_sales query:

    INSERT INTO gcpl-469311.datalabs_techtest.fact_sales 
        (transaction_id, customer_id, product_id, quantity, price)
    SELECT 
        t.transaction_id,
        t.customer_id,
        ti.product_id,
        ti.quantity,
        ti.price
    FROM gcpl-469311.datalabs_techtest.stg_transactions t 
    JOIN gcpl-469311.datalabs_techtest.stg_transaction_items ti ON t.transaction_id = ti.transaction_id
    WHERE NOT EXISTS (
        SELECT 1 
        FROM gcpl-469311.datalabs_techtest.fact_sales AS target
        WHERE target.transaction_id = t.transaction_id
        AND target.customer_id = t.customer_id
        AND target.product_id = ti.product_id
        AND target.quantity = ti.quantity
        AND target.price = ti.price
    );
    
[2025-10-14T04:42:13.547+0000] {transform.py:167} INFO - fact_sales query executed successfully.
[2025-10-14T04:42:13.548+0000] {transform.py:159} INFO - Executing dim_customers query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_customers AS target
    USING (
        SELECT
        c.customer_id ,
        c.name ,
        c.email ,
        c.city ,
        c.signup_date ,
    FROM gcpl-469311.datalabs_techtest.stg_customers c
    ) AS source
    ON target.customer_id = source.customer_id

    WHEN MATCHED THEN
    UPDATE SET
        target.name = source.name,
        target.email = source.email,
        target.city = source.city,
        target.signup_date = source.signup_date

    WHEN NOT MATCHED THEN
    INSERT (customer_id, name, email, city, signup_date)
    VALUES (source.customer_id, source.name, source.email, source.city, source.signup_date)
    ;
    
[2025-10-14T04:42:16.670+0000] {transform.py:167} INFO - dim_customers query executed successfully.
[2025-10-14T04:42:16.671+0000] {transform.py:159} INFO - Executing dim_products query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_products AS target
    USING (
        SELECT
            p.product_id ,
            p.product_name ,
            p.category ,
            p.price
        FROM gcpl-469311.datalabs_techtest.stg_products p
    ) AS source
    ON target.product_id = source.product_id

    WHEN MATCHED THEN
    UPDATE SET
        target.product_name = source.product_name,
        target.category = source.category,
        target.price = source.price

    WHEN NOT MATCHED THEN
    INSERT (product_id, product_name, category, price)
    VALUES (source.product_id, source.product_name, source.category, source.price)
    ;
    
[2025-10-14T04:42:20.828+0000] {transform.py:167} INFO - dim_products query executed successfully.
[2025-10-14T04:42:20.829+0000] {transform.py:159} INFO - Executing dim_dates query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_dates AS target
    USING (
        SELECT
            t.transaction_id ,
            t.transaction_date
        FROM gcpl-469311.datalabs_techtest.stg_transactions t
    ) AS source
    ON target.transaction_id = source.transaction_id

    WHEN MATCHED THEN
    UPDATE SET
        target.transaction_date = source.transaction_date

    WHEN NOT MATCHED THEN
    INSERT (transaction_id, transaction_date)
    VALUES (source.transaction_id, source.transaction_date);
    
[2025-10-14T04:42:23.625+0000] {transform.py:167} INFO - dim_dates query executed successfully.
[2025-10-14T04:42:23.626+0000] {transform.py:159} INFO - Executing dim_campaigns query:

    MERGE INTO gcpl-469311.datalabs_techtest.dim_campaigns AS target
    USING (
        SELECT
            mc.campaign_id ,
            mc.campaign_name ,
            mc.start_date ,
            mc.end_date ,
            mc.channel
        FROM gcpl-469311.datalabs_techtest.stg_marketing_campaigns mc
    ) AS source

    ON target.campaign_id = source.campaign_id

    WHEN MATCHED THEN
    UPDATE SET
        target.campaign_name = source.campaign_name ,
        target.start_date = source.start_date ,
        target.end_date = source.end_date ,
        target.channel = source.channel

    WHEN NOT MATCHED THEN
    INSERT (campaign_id, campaign_name, start_date, end_date, channel)
    VALUES (source.campaign_id, source.campaign_name, source.start_date, source.end_date, source.channel);
    
[2025-10-14T04:42:24.991+0000] {transform.py:170} ERROR - General error occurred: 400 Name campaign_id not found inside mc at [5:16]; reason: invalidQuery, location: query, message: Name campaign_id not found inside mc at [5:16]

Location: asia-southeast2
Job ID: d3751a5b-66f9-470c-a711-1e5e86df63f5
Traceback (most recent call last):
  File "/opt/airflow/dags/scripts/transform.py", line 162, in transform
    job.result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1681, in result
    while not is_job_done():
              ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1630, in is_job_done
    raise job_failed_exception
google.api_core.exceptions.BadRequest: 400 Name campaign_id not found inside mc at [5:16]; reason: invalidQuery, location: query, message: Name campaign_id not found inside mc at [5:16]

Location: asia-southeast2
Job ID: d3751a5b-66f9-470c-a711-1e5e86df63f5

[2025-10-14T04:42:24.998+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-14T04:42:25.011+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-14T04:42:25.011+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=elt-pipeline, task_id=transform, run_id=scheduled__2025-09-14T00:00:00+00:00, execution_date=20250914T000000, start_date=20251014T044205, end_date=20251014T044225
[2025-10-14T04:42:25.050+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-14T04:42:25.068+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-14T04:42:25.070+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
